# Generated by Django 5.2.7 on 2026-09-06 07:39

import django.db.models.deletion
import django.utils.timezone
import socos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutzer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-Mail')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('initialen', models.CharField(blank=True, max_length=4, verbose_name='Initialen')),
                ('farbe', models.CharField(default='#BFD9CE', max_length=7, verbose_name='Farbe')),
                ('funktion', models.CharField(blank=True, max_length=120, verbose_name='Funktion')),
                ('telefon', models.CharField(blank=True, max_length=40, verbose_name='Telefon')),
                ('strasse', models.CharField(blank=True, max_length=160, verbose_name='Straße')),
                ('ort', models.CharField(blank=True, max_length=120, verbose_name='Ort')),
                ('geburtsdatum', models.DateField(blank=True, null=True, verbose_name='Geburtsdatum')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Admin-Zugang')),
                ('beigetreten_am', models.DateTimeField(default=django.utils.timezone.now, verbose_name='beigetreten am')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Nutzer',
                'verbose_name_plural': 'Nutzer',
                'ordering': ['name'],
            },
            managers=[
                ('objects', socos.models.NutzerVerwaltung()),
            ],
        ),
        migrations.CreateModel(
            name='Protokolleintrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitpunkt', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Zeitpunkt')),
                ('nutzer_text', models.CharField(blank=True, max_length=160, verbose_name='Nutzer (Text)')),
                ('modell', models.CharField(db_index=True, max_length=80, verbose_name='Modell')),
                ('objekt_id', models.CharField(db_index=True, max_length=40, verbose_name='Objekt')),
                ('objekt_text', models.CharField(blank=True, max_length=250, verbose_name='Objekt (Text)')),
                ('aktion', models.CharField(choices=[('angelegt', 'angelegt'), ('geaendert', 'geändert'), ('geloescht', 'gelöscht'), ('wiederhergestellt', 'wiederhergestellt')], max_length=20, verbose_name='Aktion')),
                ('aenderungen', models.JSONField(blank=True, default=dict, verbose_name='Änderungen')),
                ('nutzer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protokolleintraege', to=settings.AUTH_USER_MODEL, verbose_name='Nutzer')),
            ],
            options={
                'verbose_name': 'Protokolleintrag',
                'verbose_name_plural': 'Änderungsprotokoll',
                'ordering': ['-zeitpunkt', '-id'],
                'indexes': [models.Index(fields=['modell', 'objekt_id', '-zeitpunkt'], name='socos_proto_modell_7e5185_idx')],
            },
        ),
    ]
