# Generated by Django 5.2.7 on 2026-09-07 20:05

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socos', '0002_rollen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bereich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='erstellt am')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('geloescht_am', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='gelöscht am')),
                ('titel', models.CharField(max_length=160, verbose_name='Titel')),
                ('art', models.CharField(choices=[('dev', 'Entwicklung'), ('fin', 'Finanzierung'), ('ziel', 'Ziele')], max_length=8, verbose_name='Art')),
                ('reihenfolge', models.IntegerField(default=0, verbose_name='Reihenfolge')),
                ('stufen', models.JSONField(blank=True, default=list, verbose_name='Stufen')),
            ],
            options={
                'verbose_name': 'Bereich',
                'verbose_name_plural': 'Bereiche',
                'ordering': ['projekt', 'reihenfolge', 'titel'],
                'abstract': False,
                'base_manager_name': 'alle_objekte',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('alle_objekte', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Fixkosten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='erstellt am')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('geloescht_am', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='gelöscht am')),
                ('gueltig_ab', models.DateField(unique=True, verbose_name='gültig ab')),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Betrag je Monat')),
            ],
            options={
                'verbose_name': 'Fixkosten',
                'verbose_name_plural': 'Fixkosten',
                'ordering': ['-gueltig_ab'],
                'abstract': False,
                'base_manager_name': 'alle_objekte',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('alle_objekte', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Kontostand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='erstellt am')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('geloescht_am', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='gelöscht am')),
                ('datum', models.DateField(unique=True, verbose_name='Stichtag')),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Kontostand')),
            ],
            options={
                'verbose_name': 'Kontostand',
                'verbose_name_plural': 'Kontostände',
                'ordering': ['-datum'],
                'abstract': False,
                'base_manager_name': 'alle_objekte',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('alle_objekte', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Monatskosten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='erstellt am')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('geloescht_am', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='gelöscht am')),
                ('monat', models.DateField(help_text='Der Erste des Monats.', unique=True, verbose_name='Monat')),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Betrag')),
            ],
            options={
                'verbose_name': 'Monatskosten',
                'verbose_name_plural': 'Monatskosten',
                'ordering': ['-monat'],
                'abstract': False,
                'base_manager_name': 'alle_objekte',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('alle_objekte', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='erstellt am')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('geloescht_am', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='gelöscht am')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('kurz', models.CharField(blank=True, max_length=8, verbose_name='Kürzel')),
                ('typ', models.CharField(blank=True, max_length=80, verbose_name='Typ')),
                ('stufe', models.CharField(choices=[('erstkontakt', 'Erstkontakt'), ('antrag', 'Antrag läuft'), ('partner', 'Partner')], default='erstkontakt', max_length=14, verbose_name='Stufe')),
                ('nutzen', models.TextField(blank=True, verbose_name='Nutzen und Interesse')),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisationen',
                'ordering': ['name'],
                'abstract': False,
                'base_manager_name': 'alle_objekte',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('alle_objekte', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Projekt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='erstellt am')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('geloescht_am', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='gelöscht am')),
                ('titel', models.CharField(max_length=160, verbose_name='Titel')),
                ('untertitel', models.CharField(blank=True, max_length=200, verbose_name='Untertitel')),
                ('farbe', models.CharField(default='#14595F', max_length=7, verbose_name='Farbe')),
                ('reihenfolge', models.IntegerField(default=0, verbose_name='Reihenfolge')),
            ],
            options={
                'verbose_name': 'Projekt',
                'verbose_name_plural': 'Projekte',
                'ordering': ['reihenfolge', 'titel'],
                'abstract': False,
                'base_manager_name': 'alle_objekte',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('alle_objekte', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Arbeitspaket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='erstellt am')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('geloescht_am', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='gelöscht am')),
                ('titel', models.CharField(max_length=250, verbose_name='Titel')),
                ('notiz', models.TextField(blank=True, verbose_name='Notiz')),
                ('status', models.CharField(choices=[('offen', 'offen'), ('laeuft', 'läuft'), ('eingereicht', 'eingereicht'), ('zugesagt', 'zugesagt'), ('fertig', 'fertig'), ('verworfen', 'verworfen'), ('offene_frage', 'offene Frage')], default='offen', max_length=14, verbose_name='Status')),
                ('stufenstand', models.IntegerField(default=0, verbose_name='Stufenstand')),
                ('reihenfolge', models.IntegerField(default=0, verbose_name='Reihenfolge')),
                ('bereich', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pakete', to='socos.bereich', verbose_name='Bereich')),
            ],
            options={
                'verbose_name': 'Arbeitspaket',
                'verbose_name_plural': 'Arbeitspakete',
                'ordering': ['bereich', 'reihenfolge', 'titel'],
                'abstract': False,
                'base_manager_name': 'alle_objekte',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('alle_objekte', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Kontakt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='erstellt am')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('geloescht_am', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='gelöscht am')),
                ('name', models.CharField(max_length=160, verbose_name='Name')),
                ('funktion', models.CharField(blank=True, max_length=160, verbose_name='Rolle')),
                ('ball', models.CharField(choices=[('uns', 'bei uns'), ('ihnen', 'bei ihnen')], default='uns', max_length=6, verbose_name='Am Zug')),
                ('offener_punkt', models.CharField(blank=True, max_length=250, verbose_name='Offener Punkt')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kontakte', to='socos.organisation', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Kontakt',
                'verbose_name_plural': 'Kontakte',
                'ordering': ['name'],
                'abstract': False,
                'base_manager_name': 'alle_objekte',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('alle_objekte', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='bereich',
            name='projekt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bereiche', to='socos.projekt', verbose_name='Projekt'),
        ),
        migrations.CreateModel(
            name='Unteraufgabe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='erstellt am')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('geloescht_am', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='gelöscht am')),
                ('titel', models.CharField(max_length=250, verbose_name='Titel')),
                ('erledigt', models.BooleanField(default=False, verbose_name='erledigt')),
                ('reihenfolge', models.IntegerField(default=0, verbose_name='Reihenfolge')),
                ('paket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unteraufgaben', to='socos.arbeitspaket', verbose_name='Arbeitspaket')),
            ],
            options={
                'verbose_name': 'Unteraufgabe',
                'verbose_name_plural': 'Unteraufgaben',
                'ordering': ['paket', 'reihenfolge', 'titel'],
                'abstract': False,
                'base_manager_name': 'alle_objekte',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('alle_objekte', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Verlaufseintrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='erstellt am')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('geloescht_am', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='gelöscht am')),
                ('datum', models.DateField(default=django.utils.timezone.localdate, verbose_name='Datum')),
                ('art', models.CharField(choices=[('meeting', 'Meeting'), ('mail', 'Mail'), ('call', 'Call'), ('event', 'Event')], max_length=10, verbose_name='Art')),
                ('titel', models.CharField(max_length=200, verbose_name='Titel')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('kontakt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verlauf', to='socos.kontakt', verbose_name='Kontakt')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verlauf', to='socos.organisation', verbose_name='Organisation')),
                ('wer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verlaufseintraege', to=settings.AUTH_USER_MODEL, verbose_name='Wer')),
            ],
            options={
                'verbose_name': 'Verlaufseintrag',
                'verbose_name_plural': 'Verlauf',
                'ordering': ['-datum', '-id'],
                'abstract': False,
                'base_manager_name': 'alle_objekte',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('kontakt__isnull', False), ('organisation__isnull', True)), models.Q(('kontakt__isnull', True), ('organisation__isnull', False)), _connector='OR'), name='verlauf_haengt_an_genau_einem')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('alle_objekte', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Zeitbuchung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='erstellt am')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('geloescht_am', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='gelöscht am')),
                ('start', models.DateTimeField(verbose_name='Start')),
                ('ende', models.DateTimeField(blank=True, null=True, verbose_name='Ende')),
                ('notiz', models.TextField(blank=True, verbose_name='Notiz')),
                ('ist_entwurf', models.BooleanField(default=False, verbose_name='Entwurf')),
                ('paket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zeitbuchungen', to='socos.arbeitspaket', verbose_name='Arbeitspaket')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zeitbuchungen', to=settings.AUTH_USER_MODEL, verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Zeitbuchung',
                'verbose_name_plural': 'Zeitbuchungen',
                'ordering': ['-start'],
                'abstract': False,
                'base_manager_name': 'alle_objekte',
                'indexes': [models.Index(fields=['person', '-start'], name='socos_zeitb_person__423224_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ende__isnull', True), ('geloescht_am__isnull', True)), fields=('person',), name='hoechstens_eine_laufende_buchung_je_person'), models.CheckConstraint(condition=models.Q(('ende__isnull', True), ('ende__gt', models.F('start')), _connector='OR'), name='ende_liegt_nach_start')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('alle_objekte', django.db.models.manager.Manager()),
            ],
        ),
    ]
