# Generated by Django 5.2.7 on 2026-09-09 09:58

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socos', '0004_stufen_am_arbeitspaket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='erstellt am')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('geloescht_am', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='gelöscht am')),
                ('titel', models.CharField(max_length=200, verbose_name='Titel')),
                ('ort', models.CharField(blank=True, max_length=160, verbose_name='Ort')),
                ('von', models.DateField(verbose_name='Von')),
                ('bis', models.DateField(blank=True, null=True, verbose_name='Bis')),
                ('notiz', models.TextField(blank=True, verbose_name='Notiz')),
                ('teilnehmer', models.ManyToManyField(blank=True, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Teilnehmer')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-von', 'titel'],
                'abstract': False,
                'base_manager_name': 'alle_objekte',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('alle_objekte', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='verlaufseintrag',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verlauf', to='socos.event', verbose_name='Event'),
        ),
        migrations.CreateModel(
            name='Eventziel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='erstellt am')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('geloescht_am', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='gelöscht am')),
                ('anliegen', models.CharField(blank=True, max_length=250, verbose_name='Anliegen')),
                ('stand', models.CharField(choices=[('offen', 'offen'), ('getroffen', 'getroffen'), ('verpasst', 'verpasst')], default='offen', max_length=10, verbose_name='Stand')),
                ('reihenfolge', models.IntegerField(default=0, verbose_name='Reihenfolge')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ziele', to='socos.event', verbose_name='Event')),
                ('kontakt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventziele', to='socos.kontakt', verbose_name='Kontakt')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventziele', to='socos.organisation', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Eventziel',
                'verbose_name_plural': 'Hitlist',
                'ordering': ['event', 'reihenfolge', 'id'],
                'abstract': False,
                'base_manager_name': 'alle_objekte',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('alle_objekte', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('bis__isnull', True), ('bis__gte', models.F('von')), _connector='OR'), name='event_endet_nicht_vor_seinem_anfang'),
        ),
        migrations.AddConstraint(
            model_name='eventziel',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kontakt__isnull', False), ('organisation__isnull', True)), models.Q(('kontakt__isnull', True), ('organisation__isnull', False)), _connector='OR'), name='eventziel_zeigt_auf_genau_eines'),
        ),
        migrations.AddConstraint(
            model_name='eventziel',
            constraint=models.UniqueConstraint(condition=models.Q(('geloescht_am__isnull', True), ('organisation__isnull', False)), fields=('event', 'organisation'), name='eine_organisation_nur_einmal_je_event'),
        ),
        migrations.AddConstraint(
            model_name='eventziel',
            constraint=models.UniqueConstraint(condition=models.Q(('geloescht_am__isnull', True), ('kontakt__isnull', False)), fields=('event', 'kontakt'), name='eine_person_nur_einmal_je_event'),
        ),
    ]
