# Generated by Django 5.2.7 on 2026-09-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socos', '0005_events_und_hitlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontakt',
            name='ball',
            field=models.CharField(choices=[('uns', 'bei uns'), ('ihnen', 'bei ihnen'), ('nichts', 'nichts offen')], default='uns', max_length=6, verbose_name='Am Zug'),
        ),
    ]
