# Generated by Django 5.2.7 on 2026-09-10 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socos', '0009_prioritaet_beschriftung'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontakt',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-Mail'),
        ),
        migrations.AddField(
            model_name='kontakt',
            name='kennengelernt_auf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kennengelernte', to='socos.event', verbose_name='Kennengelernt auf'),
        ),
        migrations.AddField(
            model_name='kontakt',
            name='telefon',
            field=models.CharField(blank=True, max_length=60, verbose_name='Telefon'),
        ),
    ]
