# Generated by Django 5.2.7 on 2026-09-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socos', '0010_kontakt_email_kontakt_kennengelernt_auf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontakt',
            name='anrede',
            field=models.CharField(blank=True, choices=[('herr', 'Herr'), ('frau', 'Frau')], max_length=4, verbose_name='Anrede'),
        ),
    ]
