# Generated by Django 5.2.7 on 2026-09-13 19:01

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socos', '0011_kontakt_anrede'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutzer',
            name='neuigkeiten_bis',
            field=models.CharField(blank=True, max_length=20, verbose_name='Neuigkeiten gesehen bis'),
        ),
        migrations.CreateModel(
            name='Rueckmeldung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='erstellt am')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('geloescht_am', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='gelöscht am')),
                ('art', models.CharField(choices=[('wunsch', 'Wunsch'), ('fehler', 'Fehler')], default='wunsch', max_length=10, verbose_name='Art')),
                ('titel', models.CharField(max_length=200, verbose_name='Titel')),
                ('text', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('stand', models.CharField(choices=[('neu', 'neu'), ('angenommen', 'angenommen'), ('in_arbeit', 'in Arbeit'), ('erledigt', 'erledigt'), ('abgelehnt', 'abgelehnt')], db_index=True, default='neu', max_length=12, verbose_name='Stand')),
                ('antwort', models.TextField(blank=True, verbose_name='Antwort')),
                ('erledigt_in', models.CharField(blank=True, max_length=20, verbose_name='Erledigt in Version')),
                ('melder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rueckmeldungen', to=settings.AUTH_USER_MODEL, verbose_name='Gemeldet von')),
            ],
            options={
                'verbose_name': 'Rückmeldung',
                'verbose_name_plural': 'Wünsche und Fehler',
                'ordering': ['-erstellt_am', '-id'],
                'abstract': False,
                'base_manager_name': 'alle_objekte',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('alle_objekte', django.db.models.manager.Manager()),
            ],
        ),
    ]
