# Generated by Django 5.2.7 on 2026-09-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socos', '0012_nutzer_neuigkeiten_bis_rueckmeldung'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbeitspaket',
            name='ist_auffang',
            field=models.BooleanField(default=False, verbose_name='Auffangpaket'),
        ),
    ]
