# Generated by Django 5.2.7 on 2026-09-14 07:07

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socos', '0013_arbeitspaket_ist_auffang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aufgabe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='erstellt am')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('geloescht_am', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='gelöscht am')),
                ('text', models.CharField(max_length=250, verbose_name='Aufgabe')),
                ('prioritaet', models.CharField(choices=[('hoch', 'hoch'), ('mittel', 'mittel'), ('gering', 'gering')], default='mittel', max_length=8, verbose_name='Priorität')),
                ('erledigt', models.BooleanField(default=False, verbose_name='erledigt')),
                ('person', models.ForeignKey(blank=True, help_text='Leer heißt: allgemein, für niemanden bestimmten.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aufgaben', to=settings.AUTH_USER_MODEL, verbose_name='Für')),
            ],
            options={
                'verbose_name': 'Aufgabe',
                'verbose_name_plural': 'Aufgaben',
                'ordering': ['-erstellt_am', '-id'],
                'abstract': False,
                'base_manager_name': 'alle_objekte',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('alle_objekte', django.db.models.manager.Manager()),
            ],
        ),
    ]
