# Generated by Django 5.2.7 on 2026-09-15 14:20

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socos', '0014_aufgabe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='erstellt am')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('geloescht_am', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='gelöscht am')),
                ('titel', models.CharField(max_length=200, verbose_name='Titel')),
                ('datum', models.DateField(default=django.utils.timezone.localdate, verbose_name='Datum')),
                ('uhrzeit', models.TimeField(blank=True, null=True, verbose_name='Uhrzeit')),
                ('ort', models.CharField(blank=True, max_length=160, verbose_name='Ort')),
                ('vorbereitung', models.TextField(blank=True, verbose_name='Vorbereitung')),
                ('mitschrift', models.TextField(blank=True, verbose_name='Mitschrift')),
                ('kontakte', models.ManyToManyField(blank=True, related_name='meetings', to='socos.kontakt', verbose_name='Personen')),
                ('organisationen', models.ManyToManyField(blank=True, related_name='meetings', to='socos.organisation', verbose_name='Organisationen')),
                ('teilnehmer', models.ManyToManyField(blank=True, related_name='meetings', to=settings.AUTH_USER_MODEL, verbose_name='Von uns')),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
                'ordering': ['-datum', models.OrderBy(models.F('uhrzeit'), descending=True, nulls_last=True), 'titel'],
                'abstract': False,
                'base_manager_name': 'alle_objekte',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('alle_objekte', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Meetingabschnitt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='erstellt am')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('geloescht_am', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='gelöscht am')),
                ('ueberschrift', models.CharField(blank=True, max_length=200, verbose_name='Überschrift')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('reihenfolge', models.IntegerField(default=0, verbose_name='Reihenfolge')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abschnitte', to='socos.meeting', verbose_name='Meeting')),
            ],
            options={
                'verbose_name': 'Protokollabschnitt',
                'verbose_name_plural': 'Protokollabschnitte',
                'ordering': ['meeting', 'reihenfolge', 'id'],
                'abstract': False,
                'base_manager_name': 'alle_objekte',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('alle_objekte', django.db.models.manager.Manager()),
            ],
        ),
    ]
