# Generated by Django 5.2.7 on 2026-09-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socos', '0015_meeting_meetingabschnitt'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabe',
            name='ist_idee',
            field=models.BooleanField(default=False, help_text='Steht auf der Ideenliste statt auf der Tafel — noch nicht entschieden.', verbose_name='Idee'),
        ),
    ]
