# Generated by Django 5.2.7 on 2026-09-21 13:44

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socos', '0020_phasenstand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vorhaben',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='erstellt am')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('geloescht_am', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='gelöscht am')),
                ('titel', models.CharField(max_length=160, verbose_name='Titel')),
            ],
            options={
                'verbose_name': 'Vorhaben',
                'verbose_name_plural': 'Vorhaben',
                'ordering': ['titel', 'id'],
                'abstract': False,
                'base_manager_name': 'alle_objekte',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('alle_objekte', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Canvaspunkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='erstellt am')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('geloescht_am', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='gelöscht am')),
                ('feld', models.CharField(choices=[('problem', 'The Problem'), ('kunden', 'Customer Segments'), ('nutzen', 'Unique Value Propositions'), ('loesung', 'The Solution'), ('vorteil', 'Unfair Advantage'), ('kanaele', 'Channels'), ('einnahmen', 'Revenue Streams'), ('kennzahlen', 'Key Metrics'), ('kosten', 'Cost Structure')], max_length=12, verbose_name='Feld')),
                ('text', models.TextField(verbose_name='Text')),
                ('reihenfolge', models.IntegerField(default=0, verbose_name='Reihenfolge')),
                ('vorhaben', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvaspunkte', to='socos.vorhaben', verbose_name='Vorhaben')),
            ],
            options={
                'verbose_name': 'Canvas-Punkt',
                'verbose_name_plural': 'Canvas-Punkte',
                'ordering': ['vorhaben', 'feld', 'reihenfolge', 'id'],
                'abstract': False,
                'base_manager_name': 'alle_objekte',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('alle_objekte', django.db.models.manager.Manager()),
            ],
        ),
    ]
