# Generated by Django 5.2.7 on 2026-09-21 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socos', '0022_das_eine_vorhaben'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvaspunkt',
            name='feld',
            field=models.CharField(choices=[('problem', 'The Problem'), ('kunden', 'Customer Segments'), ('nutzen', 'Unique Value Propositions'), ('loesung', 'The Solution'), ('vorteil', 'Unfair Advantage'), ('kanaele', 'Channels'), ('einnahmen', 'Revenue Streams'), ('kennzahlen', 'Key Metrics'), ('kosten', 'Cost Structure'), ('summary', 'Executive Summary'), ('produkte', 'Products & Services'), ('markt', 'Market Research & Analysis'), ('vertrieb', 'Marketing & Sales'), ('firma', 'Company Structure & Management'), ('sdg', 'Sustainable Development Goals'), ('finanzen', 'Financial Planning'), ('tipps', 'Tips & Tricks')], max_length=12, verbose_name='Feld'),
        ),
    ]
