# Generated by Django 5.2.7 on 2026-09-22 07:21

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socos', '0023_businessplan_lite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='erstellt am')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('geloescht_am', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='gelöscht am')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('rolle', models.CharField(choices=[('nutzer', 'Nutzer'), ('kunde', 'Kunde'), ('beides', 'Nutzer und Kunde')], default='beides', max_length=8, verbose_name='Rolle')),
                ('alter', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Alter')),
                ('geschlecht', models.CharField(blank=True, max_length=40, verbose_name='Geschlecht')),
                ('wohnort', models.CharField(blank=True, max_length=120, verbose_name='Wohnort')),
                ('beruf', models.CharField(blank=True, max_length=120, verbose_name='Beruf')),
                ('haushalt', models.CharField(blank=True, max_length=160, verbose_name='Familie und Haushalt')),
                ('einkommen', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Einkommen netto im Monat')),
                ('beduerfnisse', models.TextField(blank=True, verbose_name='Bedürfnisse und Ziele')),
                ('probleme', models.TextField(blank=True, verbose_name='Probleme und Frust')),
                ('reihenfolge', models.IntegerField(default=0, verbose_name='Reihenfolge')),
                ('vorhaben', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='socos.vorhaben', verbose_name='Vorhaben')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['vorhaben', 'reihenfolge', 'id'],
                'abstract': False,
                'base_manager_name': 'alle_objekte',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('alle_objekte', django.db.models.manager.Manager()),
            ],
        ),
    ]
