# Generated by Django 5.2.17 on 2026-09-26 09:00

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socos', '0028_vision_ein_satz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Praktikumsthema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='erstellt am')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('geloescht_am', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='gelöscht am')),
                ('titel', models.CharField(max_length=160, verbose_name='Titel')),
                ('kurzbeschreibung', models.TextField(blank=True, verbose_name='Kurzbeschreibung')),
                ('punkte', models.TextField(blank=True, help_text='Ein Punkt je Zeile.', verbose_name='Punkte')),
                ('ausschreibung', models.TextField(blank=True, verbose_name='Ausschreibung')),
            ],
            options={
                'verbose_name': 'Praktikumsthema',
                'verbose_name_plural': 'Praktikumsthemen',
                'ordering': ['titel', 'id'],
                'abstract': False,
                'base_manager_name': 'alle_objekte',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('alle_objekte', django.db.models.manager.Manager()),
            ],
        ),
    ]
