# Generated by Django 5.2.17 on 2026-09-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socos', '0029_praktikumsthema'),
    ]

    operations = [
        migrations.AddField(
            model_name='praktikumsthema',
            name='art',
            field=models.CharField(choices=[('aufgabe', 'Haupt-Aufgabenstellung'), ('idee', 'Sonstige Idee')], default='aufgabe', max_length=10, verbose_name='Art'),
        ),
    ]
