# Generated by Django 5.2.17 on 2026-09-28 19:06

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socos', '0031_aufgabe_personen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lagethema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='erstellt am')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('geloescht_am', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='gelöscht am')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('farbe', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Farbe')),
                ('x', models.IntegerField(default=0, verbose_name='x')),
                ('y', models.IntegerField(default=0, verbose_name='y')),
            ],
            options={
                'verbose_name': 'Thema der Lagekarte',
                'verbose_name_plural': 'Themen der Lagekarte',
                'ordering': ['id'],
                'abstract': False,
                'base_manager_name': 'alle_objekte',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('alle_objekte', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Lageschritt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='erstellt am')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('geloescht_am', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='gelöscht am')),
                ('titel', models.CharField(max_length=160, verbose_name='Titel')),
                ('art', models.CharField(choices=[('schritt', 'Schritt'), ('warten', 'Warten auf'), ('entscheidung', 'Entscheidung'), ('termin', 'Termin')], default='schritt', max_length=16, verbose_name='Art')),
                ('status', models.CharField(choices=[('offen', 'offen'), ('erledigt', 'erledigt')], default='offen', max_length=12, verbose_name='Status')),
                ('frist', models.DateField(blank=True, null=True, verbose_name='Frist')),
                ('notiz', models.TextField(blank=True, verbose_name='Notiz')),
                ('x', models.IntegerField(default=0, verbose_name='x')),
                ('y', models.IntegerField(default=0, verbose_name='y')),
                ('thema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schritte', to='socos.lagethema', verbose_name='Thema')),
            ],
            options={
                'verbose_name': 'Schritt der Lagekarte',
                'verbose_name_plural': 'Schritte der Lagekarte',
                'ordering': ['id'],
                'abstract': False,
                'base_manager_name': 'alle_objekte',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('alle_objekte', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Lageverbindung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='erstellt am')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('geloescht_am', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='gelöscht am')),
                ('text', models.CharField(blank=True, max_length=40, verbose_name='Beschriftung')),
                ('nach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eingaenge', to='socos.lageschritt', verbose_name='nach')),
                ('von', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausgaenge', to='socos.lageschritt', verbose_name='von')),
            ],
            options={
                'verbose_name': 'Verbindung der Lagekarte',
                'verbose_name_plural': 'Verbindungen der Lagekarte',
                'ordering': ['id'],
                'abstract': False,
                'base_manager_name': 'alle_objekte',
                'constraints': [models.UniqueConstraint(condition=models.Q(('geloescht_am__isnull', True)), fields=('von', 'nach'), name='lageverbindung_einmal'), models.CheckConstraint(condition=models.Q(('von', models.F('nach')), _negated=True), name='lageverbindung_nicht_auf_sich')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('alle_objekte', django.db.models.manager.Manager()),
            ],
        ),
    ]
