# Generated by Django 5.2.17 on 2026-09-28 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socos', '0032_lagekarte'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lageschritt',
            options={'base_manager_name': 'alle_objekte', 'ordering': ['id'], 'verbose_name': 'Schritt im Stellwerk', 'verbose_name_plural': 'Schritte im Stellwerk'},
        ),
        migrations.AlterModelOptions(
            name='lagethema',
            options={'base_manager_name': 'alle_objekte', 'ordering': ['id'], 'verbose_name': 'Thema im Stellwerk', 'verbose_name_plural': 'Themen im Stellwerk'},
        ),
        migrations.AlterModelOptions(
            name='lageverbindung',
            options={'base_manager_name': 'alle_objekte', 'ordering': ['id'], 'verbose_name': 'Verbindung im Stellwerk', 'verbose_name_plural': 'Verbindungen im Stellwerk'},
        ),
    ]
