# Generated by Django 5.2.17 on 2026-09-28 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socos', '0033_stellwerk_namen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lageschritt',
            options={'base_manager_name': 'alle_objekte', 'ordering': ['id'], 'verbose_name': 'Schritt in Thoughts', 'verbose_name_plural': 'Schritte in Thoughts'},
        ),
        migrations.AlterModelOptions(
            name='lagethema',
            options={'base_manager_name': 'alle_objekte', 'ordering': ['id'], 'verbose_name': 'Thema in Thoughts', 'verbose_name_plural': 'Themen in Thoughts'},
        ),
        migrations.AlterModelOptions(
            name='lageverbindung',
            options={'base_manager_name': 'alle_objekte', 'ordering': ['id'], 'verbose_name': 'Verbindung in Thoughts', 'verbose_name_plural': 'Verbindungen in Thoughts'},
        ),
    ]
