# Generated by Django 5.2.17 on 2026-09-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socos', '0035_eventanhang'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='beginn',
            field=models.TimeField(blank=True, null=True, verbose_name='Beginn'),
        ),
        migrations.AddField(
            model_name='event',
            name='ende',
            field=models.TimeField(blank=True, null=True, verbose_name='Ende'),
        ),
        migrations.AddField(
            model_name='nutzer',
            name='kalenderschluessel',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Kalenderschlüssel'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('ende__isnull', True), ('beginn__isnull', False), _connector='OR'), name='event_ende_nur_mit_beginn'),
        ),
    ]
