# Generated by Django 5.2.17 on 2026-10-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socos', '0036_kalender'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontakt',
            name='anknuepfen',
            field=models.TextField(blank=True, verbose_name='Gemeinsame Themen'),
        ),
        migrations.AddField(
            model_name='kontakt',
            name='hintergrund',
            field=models.TextField(blank=True, verbose_name='Hintergrund'),
        ),
        migrations.AddField(
            model_name='kontakt',
            name='meiden',
            field=models.TextField(blank=True, verbose_name='Lieber nicht ansprechen'),
        ),
    ]
