# Generated by Django 5.2.17 on 2026-10-05 19:43

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socos', '0037_kontakt_beschreibung'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foerderprogramm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='erstellt am')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('geloescht_am', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='gelöscht am')),
                ('name', models.CharField(max_length=160, verbose_name='Name')),
                ('stelle', models.CharField(blank=True, max_length=250, verbose_name='Förderstelle')),
                ('link', models.URLField(blank=True, verbose_name='Link')),
                ('max_foerderung', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Höchstförderung je Antrag')),
                ('max_monate', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Höchstlaufzeit in Monaten')),
                ('steckbrief', models.TextField(blank=True, help_text='Eine Zeile je Punkt: „Begriff: Erklärung“.', verbose_name='Richtlinie in Kürze')),
            ],
            options={
                'verbose_name': 'Förderprogramm',
                'verbose_name_plural': 'Förderprogramme',
                'ordering': ['name', 'id'],
                'abstract': False,
                'base_manager_name': 'alle_objekte',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('alle_objekte', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Foerderfrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='erstellt am')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('geloescht_am', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='gelöscht am')),
                ('frage', models.TextField(verbose_name='Frage')),
                ('antwort', models.TextField(blank=True, verbose_name='Antwort')),
                ('quelle', models.CharField(blank=True, max_length=200, verbose_name='Quelle')),
                ('reihenfolge', models.IntegerField(default=0, verbose_name='Reihenfolge')),
                ('programm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fragen', to='socos.foerderprogramm', verbose_name='Programm')),
            ],
            options={
                'verbose_name': 'Frage an die Förderstelle',
                'verbose_name_plural': 'Fragen an die Förderstelle',
                'ordering': ['reihenfolge', 'id'],
                'abstract': False,
                'base_manager_name': 'alle_objekte',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('alle_objekte', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Foerderantrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='erstellt am')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('geloescht_am', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='gelöscht am')),
                ('nummer', models.PositiveSmallIntegerField(default=1, verbose_name='Nummer')),
                ('titel', models.CharField(max_length=200, verbose_name='Kurzbezeichnung')),
                ('stand', models.CharField(choices=[('entwurf', 'Entwurf'), ('eingereicht', 'eingereicht'), ('bewilligt', 'bewilligt'), ('abgelehnt', 'abgelehnt')], default='entwurf', max_length=12, verbose_name='Stand')),
                ('foerderwerber', models.CharField(blank=True, max_length=200, verbose_name='Förderwerber')),
                ('beginn', models.DateField(blank=True, null=True, verbose_name='Geplanter Beginn')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung des Vorhabens')),
                ('nutzen', models.TextField(blank=True, verbose_name='Projektbeschreibung und Nutzen (V.4.a)')),
                ('mehrwert', models.TextField(blank=True, verbose_name='Mehrwert gegenüber Bestehendem (V.4.b)')),
                ('wirkung', models.TextField(blank=True, verbose_name='Wirkungsziele und Kennzahlen (V.4.c)')),
                ('regelbetrieb', models.TextField(blank=True, verbose_name='Kostenprognose Regelbetrieb (V.4.e)')),
                ('datenbedarf', models.TextField(blank=True, help_text='Eine Zeile je Punkt; „✓ “ davor heißt: ist da.', verbose_name='Was wir noch brauchen')),
                ('programm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='antraege', to='socos.foerderprogramm', verbose_name='Programm')),
            ],
            options={
                'verbose_name': 'Förderantrag',
                'verbose_name_plural': 'Förderanträge',
                'ordering': ['programm', 'nummer', 'id'],
                'abstract': False,
                'base_manager_name': 'alle_objekte',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('alle_objekte', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Foerderpaket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='erstellt am')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('geloescht_am', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='gelöscht am')),
                ('titel', models.CharField(max_length=200, verbose_name='Titel')),
                ('ziel', models.TextField(blank=True, verbose_name='Ziel und Inhalt')),
                ('ergebnis', models.CharField(blank=True, max_length=250, verbose_name='Ergebnis')),
                ('von', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='von Monat')),
                ('bis', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='bis Monat')),
                ('betrag', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Betrag')),
                ('reihenfolge', models.IntegerField(default=0, verbose_name='Reihenfolge')),
                ('antrag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pakete', to='socos.foerderantrag', verbose_name='Antrag')),
            ],
            options={
                'verbose_name': 'Arbeitspaket eines Antrags',
                'verbose_name_plural': 'Arbeitspakete eines Antrags',
                'ordering': ['reihenfolge', 'id'],
                'abstract': False,
                'base_manager_name': 'alle_objekte',
                'constraints': [models.CheckConstraint(condition=models.Q(('bis__gte', models.F('von'))), name='foerderpaket_bis_nach_von')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('alle_objekte', django.db.models.manager.Manager()),
            ],
        ),
    ]
