# Generated by Django 5.2.17 on 2026-10-05 20:08

from django.db import migrations, models


def bisherige_uebernehmen(apps, schema_editor):
    """Bis hierher hieß „beantwortet": eine Antwort steht da. Das bleibt so stehen."""
    Foerderfrage = apps.get_model("socos", "Foerderfrage")
    Foerderfrage.objects.exclude(antwort="").update(beantwortet=True)


class Migration(migrations.Migration):

    dependencies = [
        ('socos', '0038_foerderungen'),
    ]

    operations = [
        migrations.AddField(
            model_name='foerderfrage',
            name='beantwortet',
            field=models.BooleanField(default=False, verbose_name='beantwortet'),
        ),
        migrations.RunPython(bisherige_uebernehmen, migrations.RunPython.noop),
    ]
