# Generated by Django 5.2.17 on 2026-10-06 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socos', '0040_foerdergeber'),
    ]

    operations = [
        migrations.AddField(
            model_name='foerdergeber',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='foerdergeber', to='socos.organisation', verbose_name='Organisation'),
        ),
    ]
