# Generated by Django 5.2.17 on 2026-10-06 10:22

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socos', '0041_foerdergeber_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='foerderantrag',
            name='foerderquote',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Förderquote in %'),
        ),
        migrations.AddField(
            model_name='foerderantrag',
            name='gemeinkosten',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Gemeinkostenpauschale in %'),
        ),
        migrations.AddField(
            model_name='foerderantrag',
            name='stundensatz',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Stundensatz'),
        ),
        migrations.CreateModel(
            name='Foerderposten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='erstellt am')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('geloescht_am', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='gelöscht am')),
                ('bezeichnung', models.CharField(max_length=250, verbose_name='Bezeichnung')),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Betrag')),
                ('reihenfolge', models.IntegerField(default=0, verbose_name='Reihenfolge')),
                ('antrag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posten', to='socos.foerderantrag', verbose_name='Antrag')),
                ('paket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posten', to='socos.foerderpaket', verbose_name='Arbeitspaket')),
            ],
            options={
                'verbose_name': 'Kostenposten eines Antrags',
                'verbose_name_plural': 'Kostenposten eines Antrags',
                'ordering': ['reihenfolge', 'id'],
                'abstract': False,
                'base_manager_name': 'alle_objekte',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('alle_objekte', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Foerderstunden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='erstellt am')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('geloescht_am', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='gelöscht am')),
                ('person', models.CharField(max_length=80, verbose_name='Person')),
                ('stunden', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Stunden')),
                ('paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stunden', to='socos.foerderpaket', verbose_name='Arbeitspaket')),
            ],
            options={
                'verbose_name': 'Stunden in einem Antragspaket',
                'verbose_name_plural': 'Stunden in Antragspaketen',
                'ordering': ['paket', 'person', 'id'],
                'abstract': False,
                'base_manager_name': 'alle_objekte',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('alle_objekte', django.db.models.manager.Manager()),
            ],
        ),
    ]
