# Generated by Django 5.2.17 on 2026-10-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socos', '0042_foerderkalkulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='foerderantrag',
            name='zeitachse',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Monate im Zeitplan'),
        ),
    ]
