# Generated by Django 5.2.17 on 2026-10-07 13:17

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


# Die vier festen Texte der NÖ-Richtlinie werden je Antrag zu Abschnitten —
# mit den Überschriften, die die Seite bisher zeigte. Nur bei Anträgen, in
# denen wenigstens einer davon schon geschrieben ist: Ein KWF-Antrag, der sie
# nie hatte, soll sie auch jetzt nicht bekommen. Dort, wo es sie gibt, kommen
# alle vier, auch leere — sie sagen in der Reife weiter, was noch fehlt.
TEILE = [
    ("nutzen", "Nutzen für Pflege und Betreuung (V.4.a)"),
    ("mehrwert", "Mehrwert gegenüber Bestehendem (V.4.b)"),
    ("wirkung", "Wirkungsziele und Kennzahlen (V.4.c)"),
    ("regelbetrieb", "Kostenprognose Regelbetrieb (V.4.e)"),
]


def texte_zu_abschnitten(apps, schema_editor):
    Foerderantrag = apps.get_model("socos", "Foerderantrag")
    Foerderabschnitt = apps.get_model("socos", "Foerderabschnitt")
    for antrag in Foerderantrag.objects.all():
        if not any(getattr(antrag, feld).strip() for feld, _ in TEILE):
            continue
        for stelle, (feld, titel) in enumerate(TEILE):
            Foerderabschnitt.objects.create(
                antrag=antrag,
                titel=titel,
                text=getattr(antrag, feld),
                reihenfolge=stelle,
                geloescht_am=antrag.geloescht_am,
            )


def abschnitte_zu_texten(apps, schema_editor):
    Foerderabschnitt = apps.get_model("socos", "Foerderabschnitt")
    titel_zu_feld = {titel: feld for feld, titel in TEILE}
    for abschnitt in Foerderabschnitt.objects.select_related("antrag"):
        feld = titel_zu_feld.get(abschnitt.titel)
        if feld:
            setattr(abschnitt.antrag, feld, abschnitt.text)
            abschnitt.antrag.save(update_fields=[feld])


class Migration(migrations.Migration):

    dependencies = [
        ('socos', '0043_foerderantrag_zeitachse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foerderabschnitt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='erstellt am')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('geloescht_am', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='gelöscht am')),
                ('titel', models.CharField(max_length=200, verbose_name='Überschrift')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('reihenfolge', models.IntegerField(default=0, verbose_name='Reihenfolge')),
                ('antrag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abschnitte', to='socos.foerderantrag', verbose_name='Antrag')),
            ],
            options={
                'verbose_name': 'Textabschnitt eines Antrags',
                'verbose_name_plural': 'Textabschnitte eines Antrags',
                'ordering': ['reihenfolge', 'id'],
                'abstract': False,
                'base_manager_name': 'alle_objekte',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('alle_objekte', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunPython(texte_zu_abschnitten, abschnitte_zu_texten),
        migrations.RemoveField(
            model_name='foerderantrag',
            name='mehrwert',
        ),
        migrations.RemoveField(
            model_name='foerderantrag',
            name='nutzen',
        ),
        migrations.RemoveField(
            model_name='foerderantrag',
            name='regelbetrieb',
        ),
        migrations.RemoveField(
            model_name='foerderantrag',
            name='wirkung',
        ),
    ]
