# Generated by Django 5.2.17 on 2026-10-07 16:22

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


def _schluessel(text):
    """„B. G." und „bg" sind dasselbe Kürzel."""
    return "".join(text.split()).replace(".", "").lower()


def rolle_und_personen(apps, schema_editor):
    Foerderantrag = apps.get_model("socos", "Foerderantrag")
    Foerderstunden = apps.get_model("socos", "Foerderstunden")
    Nutzer = apps.get_model("socos", "Nutzer")

    # Einmal und nie wieder aus dem Namen: Wo ein anderer Förderwerber
    # eingetragen ist, liefern wir nur zu (bestätigt von Bernd, 2026-10-07).
    for antrag in Foerderantrag.objects.all():
        werber = antrag.foerderwerber.strip()
        if werber and "sopharmis" not in werber.lower():
            antrag.rolle = "drittleister"
            antrag.save(update_fields=["rolle"])

    # Ein Name wird nur zugeordnet, wenn er genau einen Nutzer trifft — über
    # die Initialen oder den ganzen Namen. Was zweideutig ist oder niemanden
    # trifft, bleibt als Name stehen und lässt sich in der Seite umstellen.
    treffer = {}
    for nutzer in Nutzer.objects.all():
        for wert in {nutzer.initialen, nutzer.name}:
            if wert.strip():
                treffer.setdefault(_schluessel(wert), set()).add(nutzer.pk)
    for zeile in Foerderstunden.objects.all():
        kandidaten = treffer.get(_schluessel(zeile.person), set())
        if len(kandidaten) == 1:
            zeile.nutzer_id = kandidaten.pop()
            zeile.person = ""
        elif not zeile.person.strip():
            zeile.person = "N. N."
        else:
            continue
        zeile.save(update_fields=["nutzer", "person"])


def personen_zurueck(apps, schema_editor):
    Foerderstunden = apps.get_model("socos", "Foerderstunden")
    for zeile in Foerderstunden.objects.filter(nutzer__isnull=False).select_related("nutzer"):
        zeile.person = zeile.nutzer.initialen or zeile.nutzer.name
        zeile.save(update_fields=["person"])


class Migration(migrations.Migration):

    dependencies = [
        ('socos', '0044_foerderabschnitte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foerderkapazitaet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='erstellt am')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('geloescht_am', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='gelöscht am')),
                ('stunden_je_monat', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Stunden je Monat')),
            ],
            options={
                'verbose_name': 'Förderkapazität',
                'verbose_name_plural': 'Förderkapazitäten',
                'ordering': ['nutzer', 'id'],
                'abstract': False,
                'base_manager_name': 'alle_objekte',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('alle_objekte', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='foerderantrag',
            name='rolle',
            field=models.CharField(choices=[('foerderwerber', 'Förderwerber'), ('drittleister', 'Drittleister')], default='foerderwerber', max_length=14, verbose_name='Unsere Rolle'),
        ),
        migrations.AddField(
            model_name='foerderstunden',
            name='nutzer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='foerderstunden', to=settings.AUTH_USER_MODEL, verbose_name='Nutzer'),
        ),
        migrations.AlterField(
            model_name='foerderstunden',
            name='person',
            field=models.CharField(blank=True, max_length=80, verbose_name='Person ohne Konto'),
        ),
        # Die Prüfregel „Nutzer oder Name" kommt erst in 0046: PostgreSQL
        # lässt kein ALTER TABLE zu, solange in derselben Transaktion noch
        # Fremdschlüssel-Prüfungen für geänderte Zeilen ausstehen.
        migrations.RunPython(rolle_und_personen, personen_zurueck),
        migrations.AddField(
            model_name='foerderkapazitaet',
            name='nutzer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foerderkapazitaeten', to=settings.AUTH_USER_MODEL, verbose_name='Nutzer'),
        ),
        migrations.AddConstraint(
            model_name='foerderkapazitaet',
            constraint=models.UniqueConstraint(condition=models.Q(('geloescht_am__isnull', True)), fields=('nutzer',), name='eine_foerderkapazitaet_je_nutzer'),
        ),
    ]
