# Generated by Django 5.2.17 on 2026-10-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socos', '0047_spg_academy_entfernt'),
    ]

    operations = [
        migrations.AddField(
            model_name='lagethema',
            name='abgeschlossen_am',
            field=models.DateField(blank=True, null=True, verbose_name='abgeschlossen am'),
        ),
    ]
